ModuleName    = "github.com/riita10069/roche"
ServerDir     = "generated/server"
DiDir         = "generated/app/di"
UsecaseDir    = "generated/usecase"
DomainRepoDir = "generated/domain/repository"
EntityDir     = "generated/domain/entity"
InfraModelDir = "generated/infra/model"
RepoDir       = "generated/infra/repository"
ProtoDir      = "testdata/proto"
PbGoDir       = "testdata"
ManifestsDir  = "generated/manifests"
ImageRegistry = "example.io/company"
