package gen_scaffold

import (
	. "github.com/dave/jennifer/jen"
	rocheAst "github.com/riita10069/roche/pkg/rochectl/ast"
	"go/ast"
)

func GenerateUsecase(name string, targetStruct *ast.StructType) (*File, *File) {
	properties, propertiesType := rocheAst.GetPropertyByStructAst(targetStruct)
	createArgument := rocheAst.GetPostArgument(properties, propertiesType)
	updateArgument := append(createArgument, Id("id").Int64())
	dict := GenDict(properties, properties)

	usecaseFile := NewFile("usecase")
	repositoryFile := NewFile("repository")

	usecaseFile.HeaderComment("Code generated by roche")
	repositoryFile.HeaderComment("Code generated by roche")
	repositoryFile.Type().Id("I" + name).Interface(
		Id("GetList").Params().Params(Index().Id(name), Error()),
		Id("GetByID").Params(Id("id").Int64()).Params(Id("*" +name), Error()),
		Id("Create").Params(createArgument...).Params(Id("*" +name), Error()),
		Id("Update").Params(updateArgument...).Params(Id("*" +name), Error()),
		Id("Delete").Params().Error(),
	)

	usecaseFile.Type().Id(name).Struct(
		Id(name + "Repo").Id("repository.I" + name),
	)

	// NewStructNameUsecase Constructor
	usecaseFile.Func().Id("New" + name + "Usecase").Params(Id("repo").Id("repository.I" + name)).Id("repository.I" + name).Block(
		Return(Op("&").Id(name).Values(Dict{
			Id(name + "Repo"): Id("repo"),
		})),
	)

	// GetList
	usecaseFile.Func().Params(Id("u").Id(name)).Id("GetList").Params().Params(Index().Id("*entity." +name), Error()).Block(
		List(Id("usecases"), Err()).Op(":=").
			Id("u").Dot(name+ "Repo").Dot("GetAll").Call(),

		If(
			Err().Op("!=").Nil(),
		).Block(
			Return(Id("nil"), Err()),
		),

		Return(Id("usecases"), Err()),
	)

	// GetByID
	usecaseFile.Func().Params(Id("u").Id(name)).Id("GetByID").Params(Id("id").Int64()).Params(Id("*entity." +name), Error()).Block(
		List(Id("usecase"), Err()).Op(":=").
			Id("u").Dot(name+ "Repo").Dot("GetByID").Call(Id("id")),

		If(
			Err().Op("!=").Nil(),
		).Block(
			Return(Id("nil"), Err()),
		),

		Return(Id("usecase"), Err()),
	)

	// Create
	usecaseFile.Func().Params(Id("u").Id(name)).Id("Create").Params(createArgument...).Params(Id("*entity." +name), Error()).Block(
		Id("entity").Op(":=").Op("&").Id("entity." +name).Values(dict),


		List(Id("created"), Err()).Op(":=").
			Id("u").Dot(name + "Repo").Dot("Create").Call(Id("entity")),

		If(
			Err().Op("!=").Nil(),
		).Block(
			Return(Id("nil"), Err()),
		),

		Return(Id("created"), Err()),
	)

	// Update
	usecaseFile.Func().Params(Id("u").Id(name)).Id("Update").Params(updateArgument...).Params(Id("*entity." +name), Error()).Block(
		List(Id("entity"), Err()).Op(":=").
			Id("u").Dot(name + "Repo").Dot("GetByID").Call(Id("id")),

		If(
			Err().Op("!=").Nil(),
		).Block(
			Return(Id("nil"), Err()),
		),

		Id("entity").Op("=").Op("&").Id("entity." +name).Values(dict),


		List(Id("updated"), Err()).Op(":=").
			Id("u").Dot(name + "Repo").Dot("Update").Call(
			List(Id("entity"), Id("id")),
		),


		If(
			Err().Op("!=").Nil(),
		).Block(
			Return(Id("nil"), Err()),
		),

		Return(Id("updated"), Err()),
	)

	// Delete
	usecaseFile.Func().Params(Id("u").Id(name)).Id("Delete").Params(Id("id").Int64()).Params(Error()).Block(
		List(Id("entity"), Err()).Op(":=").
			Id("u").Dot(name+ "Repo").Dot("GetByID").Call(Id("id")),

		If(
			Err().Op("!=").Nil(),
		).Block(
			Return(Id("nil"), Err()),
		),

		Err().Op(":=").
			Id("u").Dot(name + "Repo").Dot("Delete").Call(
			List(Id("entity"), Id("id")),
		),


		If(
			Err().Op("!=").Nil(),
		).Block(
			Return(Id("nil"), Err()),
		),

		Return(Err()),
	)

	return repositoryFile, usecaseFile
}
