apiVersion: v1
kind: Service
metadata:
  name: sirius-svc
  namespace: sirius-ns
  labels:
    app: sirius-label
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: sirius-label
  type: NodePort
